### ISSUE TITLE
[Entity System] Ungültiger Health-Wert bei Tod

### ISSUE THREAD

**Issue by TimK1998** [Kyraja/Lost-Kingdoms-IssueTracker#52]
Wenn man sich ohne Klasse (nur 50 Leben) von einer Hexe mit eine Instant Damage Potion bewerfen lässt stirbt man und es kommt der Error:

[10:42:28 ERROR]: Could not pass event EntityKilledEvent to lostkingdomscore v0.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at de.lostkingdoms.core.events.Event.callEvent(Event.java:51) [Core.jar:?]
        at de.lostkingdoms.core.entities.LivingEntity.die(LivingEntity.java:479) [Core.jar:?]
        at de.lostkingdoms.core.entities.LivingEntity.access$000(LivingEntity.java:64) [Core.jar:?]
        at de.lostkingdoms.core.entities.LivingEntity$1.run(LivingEntity.java:338) [Core.jar:?]
        at de.lostkingdoms.core.utils.scheduler.Scheduler$1.run(Scheduler.java:160) [Core.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.IllegalArgumentException: Health must be between 0 and 20.0(-0.4000000059604645)
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:97) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at de.lostkingdoms.core.entities.LivingEntity.setLife(LivingEntity.java:212) ~[?:?]
        at de.lostkingdoms.core.entities.EntityListener.onEntityKilledEvent(EntityListener.java:156) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        ... 15 more

Keine Ahnung ob das an den nur 50 Leben oder an der Instant Damage Potion liegt und ob das auch andere Schadensarten betrifft.

**Comment by TimK1998** [comment]
Ergänzung: Auch als Waldläufer Level 100 wird man instant gekillt.

**Comment by TimK1998** [comment]
Oh lol, das liegt daran, dass der Schaden ja jetzt prozentual interpretiert wird, aber Tim die werte noch nicht umgestellt hat, d.h. Gift mach 5000% Schaden oder so.
